# -*- coding: utf-8 -*-
"""10  Project FastApi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iYR474N0GGK8MVm41SNH_teyWBN47NM5
"""

# Commented out IPython magic to ensure Python compatibility.
# %%markdown
# # 10th Project: FASTAPI

!pip install fastapi uvicorn

# Commented out IPython magic to ensure Python compatibility.
# %%writefile main.py
# 
# from fastapi import FastAPI
# 
# # Create the FastAPI application
# app = FastAPI()
# 
# # Home route
# @app.get("/")
# def home():
#     return {
#         "message": "My FastAPI project is working"
#     }
# 
# # Student route
# @app.get("/student")
# def student():
#     return {
#         "name": "Ali",
#         "course": "Python"
#     }

!uvicorn main:app --reload